package com.capoax.kmmimages.core

import com.capoax.kmmimages.extensions.StringExtensions

data class CodeGenerator(val packageName: String, val imageInterface: String?) {
    private val images = mutableSetOf<String>()

    val result: String
        get() {
            return buildString {
                append("package $packageName\n")
                append("// Generated by CommonImages\n")
                append("data class Image(${"override ".takeIf { imageInterface != null } ?: ""}val name: String)${imageInterface?.let { ": $it" } ?: ""}\n")

                append("object Images {\n")
                images.map { image ->
                    "\tval ${StringExtensions.imageNameToConst(image)}: Image = Image(\"$image\")"
                }.forEach { line ->
                    append(line)
                    append("\n")
                }
                append("}\n\n")
            }
        }

    fun addImage(name: String) {
        images.add(name)
    }
}
