package com.capoax.kmmimages.core

data class CodeGenerator(val packageName: String) {
    var images: List<String> = emptyList()

    val result: String
        get() {
            return buildString {
                append("package $packageName")
                append("// Generated by CommonImages")
                append("data class Image(val name: String)")
                images.map {

                }
            }
            return """
            package \(packageName)
    
            // Generated by CommonImages
    
            data class Image(val name: String)
    
            object Images {
            \(images.map({ image in
                return "\tval \(image.imageNameToConst()): Image = Image(\"\(image)\")\n"
            }).joined())
            }
    
            """
        }
}
